### ISSUE TITLE
Update tape sensor threshold

### ISSUE THREAD

**Issue by davidhbrown-uri** [davidhbrown-uri/laser-scarecrow-arduino#18]
Changing levels of ambient IR light may be throwing off the tape sensor as sunlight levels change during the day.

Possible solution: If tape was sensed at initial power-on, then re-calibrate the tape sensor threshold every (half-?) hour. If tape can no longer be sensed because of ambient IR, hopefully that wouldn't last long or be too noticeable when the laser is shining places that are marked.

Variant/possible improvement: Instead of just doing it on a schedule, do it when the average light level has changed. (Maybe using that AnalogInput class.)

**Comment by davidhbrown-uri** [comment]
There is some code from the original release that will fall back to initialize if the scarecrow skips more than a couple revolutions without going back to active. At that point, it should recognize there is no ability to sense tape... but this is currently a one-way fallback. It will not at present rescan for tape after dark.

**Comment by davidhbrown** [comment]
The reflectance (tape) sensor cannot maintain detection of the low-reflectance areas (black bucket/tape) when ambient light levels are very high. The sensor returns low values for high reflectance (aluminum tape or white bucket) and high values for low reflectance. The values might be 900 vs 40 indoors but change to 120 vs 20 in bright sun. A threshold set midway between 900 and 40 (say, at dawn or dusk) would be useless at noon, resulting in loss of tape sensing.

**Comment by davidhbrown-uri** [comment]
Combination of a better shroud (looks a bit like a ST:TNG phaser!) and a better threshold calculation algorithm has largely resolved this problem.
