### ISSUE TITLE
Chatter / grinding when rotation "backs" into tape

### ISSUE THREAD

**Issue by davidhbrown-uri** [davidhbrown-uri/laser-scarecrow-arduino#45]
The scarecrow always skips over tape in the "forwards" direction, so if it reaches a taped-off section while moving backwards, it it a bit of an abrupt shock to suddenly change direction and also switch from microstepping to full stepping. Especially when the edge of the tape is not particularly smooth, this can lead to significant chatter grinding.

**Comment by davidhbrown** [comment]
resolved by skip_both_ways
