### ISSUE TITLE
Accelerate and decelerate stepper

### ISSUE THREAD

**Issue by davidhbrown** [davidhbrown-uri/laser-scarecrow-arduino#48]
The random movement of the stepper is rather harsh, especially when changing direction. Accelerating and decelerating would be appropriate. Likely implementation would be to dedicate timer T3 to the stepper pulses only, changing its frequency as needed to ramp the speed up and down. This will require #47 to get servo control out of T3.

**Comment by davidhbrown-uri** [comment]
#50 has the implementation
